import { defineStore } from 'pinia'
import { enrichMovie, enrichById, searchCollection, fetchCollectionById } from '@/services/tmdb.js'

const API_KEY_STORAGE = 'library_tmdb_key'
const CACHE_STORAGE = 'library_tmdb_cache'

function cleanCollectionTitle(title) {
  const cleaned = title
    .replace(/\b(4K|UHD|Blu-?Ray?|DVD|HD)\b/gi, '')
    .replace(/\b\d{4}\s+to\s+\d{4}\b/gi, '')
    .replace(/\b\d+[-\s]?(?:movie|film|part|disc)s?\b/gi, '')
    .replace(/\b\d+(?:st|nd|rd|th)?\s*anniversary\b/gi, '')
    .replace(/\d+(\s*[&,]\s*\d+)+/g, '')
    .replace(/\b(extended|theatrical|limited|complete|ultimate|motion picture)\b/gi, '')
    .replace(/\b(collection|trilogy|anthology|saga|set|series|edition)\b/gi, '')
    .replace(/[:\-–,]\s*$/, '')
    .replace(/\b(the|a|an)\s*$/i, '')
    .replace(/[:\-–,]\s*$/, '')
    .replace(/\s+/g, ' ')
    .trim()
  return cleaned ? `${cleaned} Collection` : title
}

export const useTmdbStore = defineStore('tmdb', {
  state: () => ({
    apiKey: localStorage.getItem(API_KEY_STORAGE) || '',
    cache: {},
    awardsCache: {},
    overrides: {},
    collections: {},
    enriching: false,
    enrichProgress: { current: 0, total: 0 },
    _cancelEnrich: false
  }),

  getters: {
    hasApiKey: (state) => !!state.apiKey,
    getMovieData: (state) => (movieId) => state.cache[movieId] || null,
    getOscarData: (state) => (movieId) => state.awardsCache[movieId] || null,
    hasOverrides: (state) => Object.keys(state.overrides).length > 0,
    getCollectionParts: (state) => (slug) => state.collections[slug]?.parts ?? [],
    getCollectionData: (state) => (slug) => state.collections[slug] ?? null,
  },

  actions: {
    async init() {
      // Load pre-built cache generated by scripts/fetch-tmdb.mjs
      try {
        const res = await fetch('/tmdb-cache.json')
        if (res.ok) this.cache = await res.json()
      } catch {}
      // Merge any per-movie overrides saved by the browser
      try {
        const raw = localStorage.getItem(CACHE_STORAGE)
        if (raw) Object.assign(this.cache, JSON.parse(raw))
      } catch {}
      // Load awards cache
      try {
        const res = await fetch('/awards-cache.json')
        if (res.ok) this.awardsCache = await res.json()
      } catch {}
      // Load file-based overrides (lowest priority)
      try {
        const res = await fetch('/tmdb-overrides.json')
        if (res.ok) Object.assign(this.overrides, await res.json())
      } catch {}
      // Merge localStorage overrides on top (higher priority)
      try {
        const raw = localStorage.getItem('library_tmdb_overrides')
        if (raw) Object.assign(this.overrides, JSON.parse(raw))
      } catch {}
      // Load collections (TMDB collection parts for isCollection rows)
      try {
        const raw = localStorage.getItem('library_tmdb_collections')
        if (raw) this.collections = JSON.parse(raw)
      } catch {}
    },

    setApiKey(key) {
      this.apiKey = key.trim()
      localStorage.setItem(API_KEY_STORAGE, this.apiKey)
    },

    _saveCache() {
      localStorage.setItem(CACHE_STORAGE, JSON.stringify(this.cache))
    },

    async fetchForMovie(movie) {
      if (this.cache[movie.id] || movie.isCollection || !this.apiKey) return
      try {
        const data = await enrichMovie(movie.title, this.apiKey)
        if (data) {
          this.cache[movie.id] = data
          this._saveCache()
        }
      } catch {
        // silently skip failed enrichments
      }
    },

    async enrichAll(movies) {
      const queue = movies.filter(m => !this.cache[m.id] && !m.isCollection)
      this.enriching = true
      this._cancelEnrich = false
      this.enrichProgress = { current: 0, total: queue.length }

      for (const movie of queue) {
        if (this._cancelEnrich) break
        await this.fetchForMovie(movie)
        this.enrichProgress.current++
        await new Promise(r => setTimeout(r, 1000))
      }

      this.enriching = false
    },

    cancelEnrich() {
      this._cancelEnrich = true
    },

    async applyOverride(movieSlug, tmdbId) {
      const data = await enrichById(tmdbId, this.apiKey)
      if (!data) return
      this.cache[movieSlug] = data
      this._saveCache()
      this.overrides[movieSlug] = tmdbId
      localStorage.setItem('library_tmdb_overrides', JSON.stringify(this.overrides))
    },

    async exportOverrides() {
      let base = {}
      try {
        const res = await fetch('/tmdb-overrides.json')
        if (res.ok) base = await res.json()
      } catch {}
      const merged = { ...base, ...this.overrides }
      const blob = new Blob([JSON.stringify(merged, null, 2)], { type: 'application/json' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'tmdb-overrides.json'
      a.click()
      URL.revokeObjectURL(url)
    },

    async fetchCollection(movie) {
      if (this.collections[movie.id] || !this.apiKey) return
      try {
        const searchTitle = cleanCollectionTitle(movie.title)
        const match = await searchCollection(searchTitle, this.apiKey)
        if (!match) return
        const data = await fetchCollectionById(match.id, this.apiKey)
        if (!data) return
        this.collections[movie.id] = data
        // Seed TMDB cache with poster data for each virtual film
        for (const part of data.parts) {
          const virtualId = `${movie.id}--${part.tmdbId}`
          if (!this.cache[virtualId] && part.posterPath) {
            this.cache[virtualId] = { posterPath: part.posterPath, year: part.year }
          }
        }
        localStorage.setItem('library_tmdb_collections', JSON.stringify(this.collections))
        this._saveCache()
      } catch {
        // silently skip failed collection fetches
      }
    },

    async fetchForMovieById(movie) {
      if (this.cache[movie.id] || !this.apiKey || !movie.tmdbId) return
      try {
        const data = await enrichById(movie.tmdbId, this.apiKey)
        if (data) {
          this.cache[movie.id] = data
          this._saveCache()
        }
      } catch {
        // silently skip
      }
    },

    clearCache() {
      this.cache = {}
      localStorage.removeItem(CACHE_STORAGE)
    },

    clearCollections() {
      this.collections = {}
      localStorage.removeItem('library_tmdb_collections')
    }
  }
})
